#app_id:
#secret:
#login:
#password:
datastore: JsonStore
update_data: 3
metric_port: 8180
fuel:
  Qashqai: 60
logging:
  handlers:
    console:
      level: INFO
    file:
      level: INFO
      filename: sds.log
      maxBytes: 1048576
      backupCount: 10
