{
 "title": "Starline",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DEVICE",
    "label": "Устройство",
    "query": {}
   },
   {
    "name": "DS",
    "query": "alexanderzobnin-zabbix-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Статус устройства $DEVICE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$DEVICE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_status/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Метка времени обновления данных",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:427",
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "1000" ],
       "text": "scale(1000)"
      },
      {
       "$$hashKey": "object:428",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+obd.+/",
        "Параметры OBD"
       ],
       "text": "replaceAlias(/.+obd.+/, Параметры OBD)"
      },
      {
       "$$hashKey": "object:429",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+e_state.+/",
        "Состояние зон охраны"
       ],
       "text": "replaceAlias(/.+e_state.+/, Состояние зон охраны)"
      },
      {
       "$$hashKey": "object:430",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+alarm_state.+/",
        "Состояние тревоги"
       ],
       "text": "replaceAlias(/.+alarm_state.+/, Состояние тревоги)"
      },
      {
       "$$hashKey": "object:431",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+activity.+/",
        "Активность устройства"
       ],
       "text": "replaceAlias(/.+activity.+/, Активность устройства)"
      },
      {
       "$$hashKey": "object:432",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+balance_(\\d)_.*/",
        "Баланс_$1"
       ],
       "text": "replaceAlias(/.+balance_(\\d)_.*/, Баланс_$1)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_.+_ts/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Периодический автозапуск",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:333",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+temp.+/",
        "По температуре"
       ],
       "text": "replaceAlias(/.+temp.+/, По температуре)"
      },
      {
       "$$hashKey": "object:331",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+cron.+/",
        "По будильнику"
       ],
       "text": "replaceAlias(/.+cron.+/, По будильнику)"
      },
      {
       "$$hashKey": "object:335",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+battery.+/",
        "По напряжению АКБ"
       ],
       "text": "replaceAlias(/.+battery.+/, По напряжению АКБ)"
      },
      {
       "$$hashKey": "object:326",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+period.+/",
        "Периодический автозапуск"
       ],
       "text": "replaceAlias(/.+period.+/, Периодический автозапуск)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_r_start/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Тревога",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:1115",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+state_(.*) .+/",
        "$1"
       ],
       "text": "replaceAlias(/.+state_(.*) .+/, $1)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": {
      "filter": "/starline_alarm_state_(?!ts).*/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:485",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+ctemp.+/",
        "Салон, t"
       ],
       "text": "replaceAlias(/.+ctemp.+/, Салон, t)"
      },
      {
       "$$hashKey": "object:486",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+gsm.+/",
        "Сигнал GSM"
       ],
       "text": "replaceAlias(/.+gsm.+/, Сигнал GSM)"
      },
      {
       "$$hashKey": "object:487",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+etemp.+/",
        "Двигатель, t"
       ],
       "text": "replaceAlias(/.+etemp.+/, Двигатель, t)"
      },
      {
       "$$hashKey": "object:488",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+battery.+/",
        "Напряжение"
       ],
       "text": "replaceAlias(/.+battery.+/, Напряжение)"
      },
      {
       "$$hashKey": "object:489",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+gps.+/",
        "Спутники GPS"
       ],
       "text": "replaceAlias(/.+gps.+/, Спутники GPS)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": {
      "filter": "/starline_common_(?!reg|.temp).+/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:514",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+ctemp.+/",
        "Салон, t"
       ],
       "text": "replaceAlias(/.+ctemp.+/, Салон, t)"
      },
      {
       "$$hashKey": "object:515",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+gsm.+/",
        "Сигнал GSM"
       ],
       "text": "replaceAlias(/.+gsm.+/, Сигнал GSM)"
      },
      {
       "$$hashKey": "object:516",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+etemp.+/",
        "Двигатель, t"
       ],
       "text": "replaceAlias(/.+etemp.+/, Двигатель, t)"
      },
      {
       "$$hashKey": "object:517",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+battery.+/",
        "Напряжение"
       ],
       "text": "replaceAlias(/.+battery.+/, Напряжение)"
      },
      {
       "$$hashKey": "object:518",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+gps.+/",
        "Спутники GPS"
       ],
       "text": "replaceAlias(/.+gps.+/, Спутники GPS)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/.*[ce]temp.+/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:543",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "$__range",
        "sum"
       ],
       "text": "aggregateBy($__range, sum)"
      },
      {
       "$$hashKey": "object:544",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Пробег" ],
       "text": "setAlias(Пробег)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_obd_mileage_delta/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:566",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Топливо" ],
       "text": "setAlias(Топливо)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_obd_fuel_percent/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Состояние устройства",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:95",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+state_(.*) .+/",
        "$1"
       ],
       "text": "replaceAlias(/.+state_(.*) .+/, $1)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_state_(?!ts).*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Температура $DEVICE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Температура",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:622",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+etemp.+/",
        "Двигатель"
       ],
       "text": "replaceAlias(/.+etemp.+/, Двигатель)"
      },
      {
       "$$hashKey": "object:620",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+ctemp.+/",
        "Салон"
       ],
       "text": "replaceAlias(/.+ctemp.+/, Салон)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_common_.temp/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Напряжение / Температура",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:102",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Температура двигателя" ],
       "text": "setAlias(Температура двигателя)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_common_etemp/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:123",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Напряжение" ],
       "text": "setAlias(Напряжение)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_common_battery/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Напряжение $DEVICE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Напряжение / События",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:134",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+state_(.*) .+/",
        "$1"
       ],
       "text": "replaceAlias(/.+state_(.*) .+/, $1)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": {
      "filter": "/starline_state_(?!ts|r_|pbrake).+/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:155",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.+state_(.*) .+/",
        "$1"
       ],
       "text": "replaceAlias(/.+state_(.*) .+/, $1)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_alarm_state_(?!ts)/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:176",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Напряжение" ],
       "text": "setAlias(Напряжение)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_common_battery/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Топливо $DEVICE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Топливо / пройденное расстояние",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "litre" }
   ],
   "targets": [
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:252",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10m",
        "sum"
       ],
       "text": "aggregateBy(10m, sum)"
      },
      {
       "$$hashKey": "object:254",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Пройденное расстояние" ],
       "text": "setAlias(Пройденное расстояние)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_obd_mileage_delta/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/$DEVICE/" },
     "functions": [
      {
       "$$hashKey": "object:277",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Топливо в баке" ],
       "text": "setAlias(Топливо в баке)"
      }
     ],
     "group": { "filter": "Starline" },
     "host": { "filter": "MyStarline" },
     "item": { "filter": "/starline_user_fuel_litres/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}